[package]
name = "protalko-infrastructure"
version.workspace = true
edition.workspace = true

[dependencies]
protalko-domain = { path = "../protalko-domain"}
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
uuid.workspace = true
